name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.13.*
- bioio >=3.2.0,<4
- ipykernel >=7.1.0,<8
- matplotlib >=3.10.8,<4
- scyjava >=1.12.1,<2
- pip
- pip:
  - pyrallis>=0.3.1, <0.4
  - bioio-czi>=2.4.2, <3
  - bioio-dv>=1.2.0, <2
  - bioio-imageio>=1.3.0, <2
  - bioio-lif>=1.4.1, <2
  - bioio-nd2>=1.5.0, <2
  - bioio-ome-tiff>=1.4.0, <2
  - bioio-ome-zarr>=3.2.1, <4
  - bioio-tifffile>=1.3.0, <2
  - bioio-bioformats>=1.3.2, <2
