name: microflow
channels:
  - bioconda
  - omnia
  - conda-forge
dependencies:
  - python=3.10
  - python-bioformats
  - matplotlib
  - tqdm
  - dask
  - h5py
  - pip
  - yaml
  - zarr
  - numpy
  - ipykernel
  - scikit-image
  - aicsimageio
  - nd2
  - papermill
  - bioformats_jar
  - joblib
  - fiji
  - pyimagej
  - openjdk
  - pip:
    - m2stitch  
